name: apiverve_htmlentities
description: HTML Entities Encoder/Decoder is a tool for encoding and decoding HTML entities. It converts special characters to HTML entities and vice versa to prevent XSS attacks and display special characters properly.
version: 1.1.14
homepage: https://apiverve.com/marketplace/htmlentities?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/htmlentities-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
